config/routes.rb
CurrencyTracker::Application.routes.draw do
  root :to => "application#welcome"

  resources :user_sessions, only: [:new, :create]
  resource  :user_sessions, only: [:destroy]

  resources :users, only: [:new, :create]

  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  namespace :api do
    resources :countries, only: [:index, :show] do
      collection do
        get :visits_over_time
        get :visited
        get :unvisited
      end
      member do
        post :visit
      end
    end

    resources :currencies, only: [:index, :show] do
      collection do
        get :collected_over_time
        get :collected
      end
    end
    post 'token' => 'base#token'
  end

end

app/models/country.rb
class Country < ActiveRecord::Base
  self.primary_key = :code

  validates :name, :code, presence: true
  validates :code, uniqueness: true

  # old assoc was has_many :/
  # I believe there are no countries having multiple currencies
  has_one :currency

  has_many :visits, foreign_key: :code
  has_many :users, through: :visits

  scope :visited_by_user, ->(user) {
    eager_load(:visits).where('visits.user_id = ?', user.id)
  }
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  self.primary_key = :code

  validates :name, :code, :weight, :collector_value, presence: true
  validates :code, uniqueness: true

  belongs_to :country

  scope :with_weight, ->(weight) { where(weight: weight).take }
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :email, presence: true, uniqueness: true

  with_options if: :password_required? do |user|
    user.validates :password, length: { minimum: 3 }
    user.validates :password, presence: true
    user.validates :password_confirmation, presence: true
    user.validates :password, confirmation: true
  end

  has_many :visits
  has_many :countries, through: :visits
  has_many :currencies, through: :countries

  def set_authentication_token
    loop do
      self.authentication_token = SecureRandom.hex.to_s
      break unless self.class.exists?(authentication_token: authentication_token)
    end
    save!
  end

  def as_json(options = {})
    super options.merge(only: :authentication_token)
  end

  private

  def password_required?
    crypted_password.blank? || !password.blank?
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  # remove default ordering error
  # SELECT  "visits".* FROM "visits"  ORDER BY "visits"."" DESC LIMIT 1
  default_scope { order(:user_id) }

  belongs_to :user
  belongs_to :country, foreign_key: :code

  scope :by_user_and_date, -> (user, opts = {}) do
    _scope = where(user_id: user.id).order(:created_at)
    if opts[:start_date] && opts[:end_date]
      _scope = _scope.where('created_at BETWEEN ? AND ?',
                            opts[:start_date],
                            opts[:end_date])
    end
  end
end

app/controllers/api/base_controller.rb
# API namespace
module Api
  # API base controller
  class BaseController < ApplicationController
    skip_before_action :require_login
    skip_before_action :verify_authenticity_token
    before_filter :restrict_access, except: :token

    rescue_from Exception, with: :render_500
    rescue_from ActionController::ParameterMissing, with: :render_400

    def token
      if login(params[:email], params[:password])
        current_user.set_authentication_token
        render json: current_user
      else
        render json: { error: 'No such user' }
      end
    end

    private

    def render_400(exception)
      render json: { error: exception.message }, status: 400
    end

    def render_500(exception)
      if Rails.env.test?
        puts exception.message
        puts exception.backtrace
      end
      render json: { error: exception.message }, status: 500
    end

    def restrict_access_method
      if Rails.configuration.allow_url_token && params[:token]
        :authenticate_with_url_token
      else
        :authenticate_with_http_token
      end
    end

    def restrict_access
      send(restrict_access_method, &restrict_access_code) ||
        (render json: { message: 'Invalid API Token' }, status: 401)
    end

    def restrict_access_code
      lambda do |token, _options = {}|
        @current_user = User.find_by(authentication_token: token)
      end
    end

    def authenticate_with_url_token
      yield params[:token]
    end
  end
end

app/controllers/api/countries_controller.rb
module Api
  class CountriesController < BaseController
    respond_to :json

    expose(:countries) { Country.all }
    expose(:visited_countries) { Country.visited_by_user(current_user) }
    expose(:country)
    expose(:visits) { Visit.by_user_and_date(current_user, params) }

    expose(:unvisited_countries) { Capacity.new(params[:capacity].to_f, current_user).run }
    expose(:unvisited_grouped) do
      unvisited_countries.each_with_object(Hash.new(0)) do |name, hsh|
        hsh[name] += 1
      end.invert
    end

    def index
    end

    def show
    end

    def visits_over_time
    end

    def visited
    end

    def unvisited
    end

    def visit
      current_user.visits.create!(country: country)
      head :ok
    end
  end
end

app/controllers/api/currencies_controller.rb
module Api
  class CurrenciesController < BaseController
    respond_to :json

    expose(:currencies)
    expose(:currency)
    expose(:visits) { Visit.by_user_and_date(current_user, params) }
    expose(:collected_currencies) do
      visits.map(&:country).map(&:currency)
    end

    def index
    end

    def show
    end

    def collected
    end

    def collected_over_time
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login, except: :not_authenticated

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  def not_authenticated
    redirect_to new_user_session_path, alert: 'Please login first.'
  end

  def welcome
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login
  expose(:user)

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(login_path, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login
  expose(:user, attributes: :user_params)

  def create
    if user.save
      auto_login(user)
      redirect_to root_path,
        notice: t(:user_created, user_params)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/application/welcome.html.erb
<h2>Welcome to Currency Tracker</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CurrencyTracker</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>

<header>
  <h1>CurrencyTracker</h1>
  <nav>
    <ul>
      <% if current_user %>
        <li><%= link_to "Logout", :logout, method: :delete %></li>
      <% else %>
        <li><%= link_to "Register", new_user_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
</header>

<%= yield %>

<footer>
  CurrencyTracker &copy; Copyright 2011 by Smart Enterprises.
</footer>
</body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>